
[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
thickness = 0.15

  [cursor.style]
  shape = "Beam"
  blinking = "Always"

[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/github_dark_default.toml"
]

[window]
dynamic_title = true

[font]
size = 11
normal.family = "JetBrainsMono"
bold.family = "JetBrainsMono"
italic.family = "JetBrainsMono"
bold_italic.family = "JetBrainsMono"
